#!/usr/bin/env python3

import click
from blockchain import BlockChain
from start import start as startProgram
from server import startServer


@click.group()
def main():
    click.echo("Starting")


@main.command()
def start():
    startProgram()
    print("Starting server now...\n")
    startServer()


main()
